import Link from 'next/link'
import { ArrowRight, CalendarDays, CheckCircle2, ChevronRight, ShieldCheck } from 'lucide-react'
import { getPublicPackages } from '../../src/data/public-catalog'
export const dynamic = 'force-dynamic'
function label(type: string) { return type === 'HAJI_KHUSUS' ? 'HAJI KHUSUS' : 'UMRAH' }
export default async function PackagesPage() {
 const packages=await getPublicPackages()
 return <main className="catalogPage"><header className="catalogHero"><div className="catalogHeroInner"><Link href="/" className="catalogBack">← HAJI TRAVEL OS</Link><span className="sectionKicker">JOURNEY COLLECTION</span><h1>Program yang<br/><em>terkelola dengan jelas.</em></h1><p>Program publik hanya tampil setelah dipublikasikan dari operating system. Tidak ada harga, kuota, atau jadwal yang dibuat-buat di sisi publik.</p></div></header><section className="catalogSection"><div className="catalogSectionHead"><div><span className="sectionKicker">PUBLISHED PROGRAMS</span><h2>Choose your<br/><em>next journey.</em></h2></div><Link href="/inquire" className="catalogOutline">Konsultasi <ArrowRight size={15}/></Link></div>{packages.length===0?<div className="catalogEmpty"><ShieldCheck size={25}/><h3>Belum ada program yang dipublikasikan.</h3><p>Tim travel dapat menerbitkan program dari operating system. Sementara itu, Anda dapat mengirim kebutuhan perjalanan untuk dikonsultasikan.</p><Link href="/inquire" className="goldButton">Mulai konsultasi <ArrowRight size={16}/></Link></div>:<div className="catalogGrid">{packages.map((item,index)=><article className="catalogCard" key={item.id}><div className={'catalogVisual catalogVisual'+((index%3)+1)}><span>{label(item.package_type)}</span><b>0{index+1}</b><div className="catalogHalo"/><strong>{item.name}</strong></div><div className="catalogBody"><div className="catalogMeta"><span>{item.package_code}</span><span>Published</span></div><h3>{item.name}</h3><p>Program resmi yang dikelola melalui HAJI TRAVEL OS. Detail itinerary dan layanan diberikan setelah konsultasi sesuai program yang dipilih.</p><Link href={'/packages/'+item.id}>Lihat detail program <ChevronRight size={15}/></Link></div></article>)}</div>}</section><section className="catalogTrust"><div><CheckCircle2/><b>Published data only</b><span>Informasi publik berasal dari program yang sudah dipublikasikan.</span></div><div><CalendarDays/><b>Schedule-aware</b><span>Keberangkatan ditampilkan hanya ketika tersedia di sistem.</span></div><div><ShieldCheck/><b>Controlled access</b><span>Data jamaah, finance, dan compliance tidak dibuka ke publik.</span></div></section></main>
}
