import React,{useState} from 'react';
import {Alert,Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {StatusBar} from 'expo-status-bar';
import * as SecureStore from 'expo-secure-store';
import QRCode from 'react-native-qrcode-svg';

type Tab='home'|'journey'|'docs'|'family'|'profile';
const C={e:'#0d3b36',g:'#c8a45d',i:'#17312d',c:'#f7f3ea'};
const steps=[['PERSIAPAN','Kelengkapan dokumen','READY'],['MANASIK','Pembekalan','PLANNED'],['BERANGKAT','Departure control','PLANNED'],['MADINAH','Kedatangan','PLANNED'],['MAKKAH','Ibadah & pendampingan','PLANNED'],['PULANG','Kepulangan','PLANNED']];
export default function App(){
 const [tab,setTab]=useState<Tab>('home'),[logged,setLogged]=useState(false),[offline,setOffline]=useState(false);
 const login=async()=>{await SecureStore.setItemAsync('hajitravel.session','demo');setLogged(true)};
 const logout=async()=>{await SecureStore.deleteItemAsync('hajitravel.session');setLogged(false)};
 return <View style={s.root}><StatusBar style="light"/><View style={s.header}><Text style={s.brand}>HAJITRAVEL<Text style={s.mini}>  PILGRIM</Text></Text><View style={s.dot}/></View>
 <ScrollView contentContainerStyle={s.body}><Text style={s.eyebrow}>JAMAAH APP · {offline?'OFFLINE READY':'ONLINE'}</Text><Text style={s.h1}>{tab==='home'?'Perjalanan Anda':tab==='journey'?'Timeline Perjalanan':tab==='docs'?'Kesiapan Dokumen':tab==='family'?'Keluarga & Pendamping':'Akun Saya'}</Text>
 {!logged?<Card><Text style={s.title}>Ruang perjalanan pribadi</Text><Text style={s.muted}>Akses timeline, readiness, Digital Pilgrim ID, keluarga dan bantuan perjalanan.</Text><Button text="Masuk ke HAJITRAVEL" onPress={login}/></Card>:<>{tab==='home'&&<Home setTab={setTab}/>} {tab==='journey'&&<Journey/>} {tab==='docs'&&<Docs/>} {tab==='family'&&<Family/>} {tab==='profile'&&<Profile offline={offline} setOffline={setOffline} logout={logout}/>}</>}</ScrollView>
 <View style={s.nav}>{(['home','journey','docs','family','profile'] as Tab[]).map(x=><Pressable key={x} onPress={()=>setTab(x)} style={[s.navItem,tab===x&&s.active]}><Text style={[s.navText,tab===x&&s.navTextActive]}>{({home:'Beranda',journey:'Jalan',docs:'Dokumen',family:'Keluarga',profile:'Akun'}[x])}</Text></Pressable>)}</View></View>
}
function Home({setTab}:{setTab:(x:Tab)=>void}){return <><View style={s.hero}><Text style={s.kicker}>PERJALANAN IBADAH</Text><Text style={s.heroTitle}>Perjalanan Anda, kami jaga.</Text><Text style={s.heroCopy}>Milestone, dokumen, keberangkatan dan bantuan dalam satu ruang pribadi.</Text></View><View style={s.grid}><Small t="Readiness" v="READY" on={()=>setTab('docs')}/><Small t="Digital ID" v="AKTIF" on={()=>Alert.alert('Digital ID','QR internal HAJITRAVEL. Bukan paspor, visa atau boarding pass.')}/><Small t="Timeline" v="1 / 6" on={()=>setTab('journey')}/><Small t="Keluarga" v="TERHUBUNG" on={()=>setTab('family')}/></View><Card><Text style={s.title}>Digital Pilgrim ID</Text><View style={s.qr}><QRCode value="hajitravel://pilgrim/demo" size={132}/></View><Text style={s.mutedCenter}>Tunjukkan hanya kepada petugas HAJITRAVEL berwenang.</Text></Card><Card><Text style={s.title}>Bantuan perjalanan</Text><Text style={s.muted}>Ikuti kanal resmi travel. Untuk keadaan darurat, ikuti prosedur lokal dan instruksi petugas.</Text></Card></>}
function Journey(){return <>{steps.map((x,i)=><Card key={x[0]}><View style={s.row}><View style={[s.dotStep,i===0&&s.done]}/><View style={{flex:1}}><Text style={s.title}>{x[0]}</Text><Text style={s.muted}>{x[1]}</Text><Text style={s.status}>{x[2]}</Text></View></View></Card>)}</>}
function Docs(){return <><Card><Text style={s.title}>Readiness</Text><Text style={s.big}>Kesiapan perjalanan</Text><Text style={s.muted}>Status berasal dari data HAJITRAVEL OS.</Text></Card>{[['Identitas','VERIFIED'],['Paspor','PENDING'],['Visa','PENDING'],['Kesehatan','PENDING']].map(x=><Card key={x[0]}><View style={s.between}><Text style={s.title}>{x[0]}</Text><Text style={s.status}>{x[1]}</Text></View></Card>)}</>}
function Family(){return <><Card><Text style={s.title}>Circle perjalanan</Text><Text style={s.muted}>Hubungkan keluarga atau guardian sesuai consent. Lokasi tidak dibagikan otomatis.</Text><Button text="Kelola consent" onPress={()=>Alert.alert('Privasi','Location sharing dan health signal berbasis consent, tujuan, waktu dan role.')}/></Card><Card><Text style={s.title}>Guardian</Text><Text style={s.muted}>Belum ada guardian aktif.</Text></Card></>}
function Profile(p:{offline:boolean,setOffline:(v:boolean)=>void,logout:()=>void}){return <><Card><Text style={s.title}>Mode perjalanan</Text><View style={s.between}><Text style={s.muted}>Simpan data minimum untuk akses offline</Text><Pressable onPress={()=>p.setOffline(!p.offline)}><Text style={s.status}>{p.offline?'AKTIF':'NONAKTIF'}</Text></Pressable></View></Card><Card><Text style={s.title}>Keamanan</Text><Text style={s.muted}>Sesi perangkat memakai secure storage. Data sensitif tidak disimpan di QR.</Text><Button text="Keluar" onPress={p.logout}/></Card></>}
function Card({children}:{children:React.ReactNode}){return <View style={s.card}>{children}</View>}
function Button({text,onPress}:{text:string,onPress:()=>void}){return <Pressable onPress={onPress} style={s.button}><Text style={s.buttonText}>{text}</Text></Pressable>}
function Small({t,v,on}:{t:string,v:string,on:()=>void}){return <Pressable onPress={on} style={s.small}><Text style={s.muted}>{t}</Text><Text style={s.smallValue}>{v}</Text></Pressable>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:C.c},header:{paddingTop:58,paddingHorizontal:22,paddingBottom:18,backgroundColor:C.e,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},brand:{fontSize:19,fontWeight:'800',letterSpacing:2,color:'#fff'},mini:{fontSize:9,color:C.g},dot:{width:11,height:11,borderRadius:8,backgroundColor:C.g},body:{padding:18,paddingBottom:120},eyebrow:{fontSize:10,letterSpacing:1.4,color:C.g,fontWeight:'800',marginBottom:5},h1:{fontSize:29,fontWeight:'800',color:C.i,marginBottom:15},hero:{backgroundColor:C.e,borderRadius:26,padding:24,marginBottom:14},kicker:{color:C.g,fontWeight:'800',fontSize:10,letterSpacing:1.5},heroTitle:{color:'#fff',fontSize:27,fontWeight:'800',marginTop:8},heroCopy:{color:'#d9e4df',lineHeight:21,marginTop:10},grid:{flexDirection:'row',flexWrap:'wrap',gap:10},small:{width:'48%',backgroundColor:'#fff',borderRadius:18,padding:17,minHeight:92},smallValue:{fontSize:18,fontWeight:'800',color:C.i,marginTop:10},card:{backgroundColor:'#fff',borderRadius:20,padding:18,marginBottom:12,borderWidth:1,borderColor:'#e9e3d6'},title:{fontSize:17,fontWeight:'800',color:C.i,marginBottom:6},muted:{color:'#66736f',lineHeight:20},mutedCenter:{color:'#66736f',lineHeight:18,textAlign:'center'},big:{fontSize:22,fontWeight:'800',color:C.i,marginVertical:8},button:{backgroundColor:C.e,borderRadius:14,paddingVertical:13,marginTop:15,alignItems:'center'},buttonText:{color:'#fff',fontWeight:'800'},row:{flexDirection:'row',gap:14},between:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:10},dotStep:{width:12,height:12,borderRadius:8,backgroundColor:'#d7d1c4',marginTop:5},done:{backgroundColor:C.g},status:{fontSize:10,fontWeight:'800',letterSpacing:1,color:C.g,marginTop:8},qr:{alignItems:'center',padding:14},nav:{position:'absolute',left:10,right:10,bottom:12,backgroundColor:C.e,borderRadius:22,padding:7,flexDirection:'row',justifyContent:'space-around',elevation:8},navItem:{paddingVertical:10,paddingHorizontal:10,borderRadius:15},active:{backgroundColor:'#1d554e'},navText:{color:'#b8cbc5',fontSize:11,fontWeight:'700'},navTextActive:{color:'#fff'}});