'use server'
import { revalidatePath } from 'next/cache'
import { requireCapability } from '../../src/access/runtime'
import { createServerSupabaseClient } from '../../src/lib/supabase/server'
const v=(f:FormData,k:string)=>String(f.get(k)??'').trim()
const n=(f:FormData,k:string)=>v(f,k)||null
const req=(f:FormData,k:string)=>{const x=v(f,k);if(!x)throw new Error('INVALID_ID');return x}
export async function addRegistrationDocument(f:FormData){const a=await requireCapability('registration.update');const s=await createServerSupabaseClient();const rid=req(f,'registration_id');const {data:r}=await s.schema('jamaah').from('registrations').select('id').eq('id',rid).eq('organization_id',a.organizationId).single();if(!r)throw new Error('REGISTRATION_NOT_FOUND');const {error}=await s.schema('jamaah').from('registration_documents').insert({organization_id:a.organizationId,registration_id:rid,document_type:v(f,'document_type'),document_no:n(f,'document_no'),storage_uri:n(f,'storage_uri'),expires_at:n(f,'expires_at'),status:v(f,'status')||'PENDING'});if(error)throw new Error(error.message);revalidatePath('/readiness-admin')}
export async function updateRegistrationDocument(f:FormData){await requireCapability('registration.update');const s=await createServerSupabaseClient();const id=req(f,'id');const {error}=await s.schema('jamaah').from('registration_documents').update({document_type:v(f,'document_type'),document_no:n(f,'document_no'),storage_uri:n(f,'storage_uri'),expires_at:n(f,'expires_at'),status:v(f,'status')}).eq('id',id);if(error)throw new Error(error.message);revalidatePath('/readiness-admin')}
export async function updateRegistrationFulfillment(f:FormData){const a=await requireCapability('registration.update');const s=await createServerSupabaseClient();const rid=req(f,'registration_id'),did=req(f,'departure_id');const {data:r}=await s.schema('jamaah').from('registrations').select('id').eq('id',rid).eq('organization_id',a.organizationId).single();if(!r)throw new Error('REGISTRATION_NOT_FOUND');const p={organization_id:a.organizationId,registration_id:rid,departure_id:did,status:v(f,'status')||'PENDING',manifest_ready:v(f,'manifest_ready')==='true',flight_ready:v(f,'flight_ready')==='true',hotel_ready:v(f,'hotel_ready')==='true',transport_ready:v(f,'transport_ready')==='true',checklist_ready:v(f,'checklist_ready')==='true',notes:n(f,'notes')};const {data:e}=await s.schema('operations').from('registration_fulfillment').select('id').eq('registration_id',rid).eq('organization_id',a.organizationId).maybeSingle();const q=e?s.schema('operations').from('registration_fulfillment').update(p).eq('id',e.id):s.schema('operations').from('registration_fulfillment').insert(p);const {error}=await q;if(error)throw new Error(error.message);revalidatePath('/readiness-admin');revalidatePath('/operations')}
