'use client'
import { FormEvent, Suspense, useState } from 'react'
import { createBrowserClient } from '@supabase/ssr'
import { useSearchParams } from 'next/navigation'
import Link from 'next/link'
import { ArrowRight, ShieldCheck, UserPlus } from 'lucide-react'
import { HaajiLogo } from '../../src/components/HaajiLogo'

function client(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(!url||!key)throw new Error('HAJITRAVEL Supabase target is not configured.');return createBrowserClient(url,key)}
function LoginForm(){const params=useSearchParams();const next=params.get('next')||'/admin';const [identity,setIdentity]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const email=identity.includes('@')?identity.trim():identity.trim().toLowerCase()+'@gmail.com';const {error}=await client().auth.signInWithPassword({email,password});if(error)throw error;window.location.assign(next.startsWith('/')?next:'/admin')}catch(err){setError(err instanceof Error?err.message:'Login gagal.')}finally{setBusy(false)}}return <div className="loginBox"><div className="loginTop"><div className="loginIcon"><ShieldCheck/></div><span className="eyebrow">HAJITRAVEL OS · SECURE PORTAL</span><h1>Selamat datang.</h1><p>Masuk ke dashboard untuk mengelola jamaah, paket, operasi, finance, dan compliance.</p></div><form onSubmit={submit}><label>Email / Username<input value={identity} onChange={e=>setIdentity(e.target.value)} placeholder="dwahyudi8377 atau email Anda" required autoComplete="username"/></label><label>Password<input value={password} onChange={e=>setPassword(e.target.value)} type="password" required autoComplete="current-password"/></label>{error&&<div className="loginError" role="alert">{error}</div>}<button className="loginButton" disabled={busy} type="submit">{busy?'Memproses…':'Sign in ke dashboard'} <ArrowRight size={16}/></button></form><div className="loginLinks"><span>Belum punya akun?</span><Link href="/signup"><UserPlus size={14}/> Sign up</Link></div><div className="loginFoot"><ShieldCheck size={14}/> Organization scope · RBAC · RLS protected</div></div>}
export default function LoginPage(){return <main className="loginPage"><div className="loginBrand"><HaajiLogo/><span>SECURE OPERATIONS PORTAL</span></div><Suspense fallback={<div className="loginBox"><p>Memuat autentikasi…</p></div>}><LoginForm/></Suspense><p className="loginEnv">HAJI TRAVEL OS · PRODUCTION PORTAL</p></main>}