'use client'
import { FormEvent, Suspense, useState } from 'react'
import { createBrowserClient } from '@supabase/ssr'
import { useSearchParams } from 'next/navigation'
import { ArrowRight, ShieldCheck } from 'lucide-react'
import { HaajiLogo } from '../../src/components/HaajiLogo'
function client(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(!url||!key)throw new Error('HAJITRAVEL Supabase target is not configured.');return createBrowserClient(url,key)}
function LoginForm(){const params=useSearchParams();const next=params.get('next')||'/admin';const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const {error}=await client().auth.signInWithPassword({email,password});if(error)throw error;window.location.assign(next.startsWith('/')?next:'/admin')}catch(err){setError(err instanceof Error?err.message:'Login gagal.')}finally{setBusy(false)}}return <div className="loginBox"><div className="loginTop"><div className="loginIcon"><ShieldCheck/></div><span className="eyebrow">HAJITRAVEL OS · AUTHENTICATION</span><h1>Welcome back.</h1><p>Masuk ke control room untuk mengelola operasi Haji & Umrah.</p></div><form onSubmit={submit}><label>Email<input value={email} onChange={e=>setEmail(e.target.value)} type="email" required autoComplete="email"/></label><label>Password<input value={password} onChange={e=>setPassword(e.target.value)} type="password" required autoComplete="current-password"/></label>{error&&<div className="loginError" role="alert">{error}</div>}<button className="loginButton" disabled={busy} type="submit">{busy?'Memproses…':'Masuk ke dashboard'} <ArrowRight size={16}/></button></form><div className="loginFoot"><ShieldCheck size={14}/> Organization scope · RBAC · RLS protected</div></div>}
export default function LoginPage(){return <main className="loginPage"><div className="loginBrand"><HaajiLogo/><span>SECURE OPERATIONS PORTAL</span></div><Suspense fallback={<div className="loginBox"><p>Memuat autentikasi…</p></div>}><LoginForm/></Suspense><p className="loginEnv">STAGING ENVIRONMENT · HAJI TRAVEL OS</p></main>}
