import Link from 'next/link'
import { requireCapability } from '../../src/access/runtime'
import { createServerSupabaseClient } from '../../src/lib/supabase/server'
import { createJourneyEvent,updateJourneyEvent } from './actions'
export const dynamic='force-dynamic'
export default async function Page(){
 const a=await requireCapability('journey.read'); const s=await createServerSupabaseClient()
 const [{data:e},{data:r},{data:d}]=await Promise.all([
  s.schema('operations').from('pilgrim_journey_events').select('*').eq('organization_id',a.organizationId).order('created_at',{ascending:false}),
  s.schema('jamaah').from('registrations').select('id,registration_no,jamaah_id').eq('organization_id',a.organizationId).order('created_at',{ascending:false}),
  s.schema('operations').from('departures').select('id,departure_code,departure_date').eq('organization_id',a.organizationId).order('departure_date')
 ])
 const ji=[...new Set((r??[]).map(x=>x.jamaah_id))]; const {data:j}=ji.length?await s.schema('jamaah').from('profiles').select('id,full_name,jamaah_no').in('id',ji):{data:[]}
 const rm=new Map((r??[]).map(x=>[x.id,x.registration_no])); const jm=new Map((j??[]).map(x=>[x.id,x.jamaah_no+' · '+x.full_name])); const dm=new Map((d??[]).map(x=>[x.id,x.departure_code+' · '+x.departure_date]))
 return <main className='controlPage'><div className='moduleHero'><div><span className='eyebrow'>PHASE 21 · PILGRIM JOURNEY ENGINE</span><h1>Journey Control</h1><p>Operational timeline for each registered pilgrim: milestones, handoffs, exceptions and evidence.</p></div><div className='moduleHeroStamp'>JOURNEY<br/>CONTROL</div></div><div className='controlBack'><Link href='/admin'>← Admin Control Center</Link><Link href='/readiness-admin'>Readiness →</Link></div>
 <section className='sectionCard'><div className='dashHead'><div><span className='eyebrow'>NEW MILESTONE</span><h3>Record journey event</h3></div></div><form action={createJourneyEvent} className='controlForm'><select name='registration_id' className='controlInput' required><option value=''>Registration…</option>{(r??[]).map(x=><option key={x.id} value={x.id}>{x.registration_no} · {jm.get(x.jamaah_id)??'Jamaah'}</option>)}</select><select name='departure_id' className='controlInput' required><option value=''>Departure…</option>{(d??[]).map(x=><option key={x.id} value={x.id}>{x.departure_code} · {x.departure_date}</option>)}</select><input name='event_code' className='controlInput' placeholder='Event code e.g. AIRPORT_CHECKIN' required/><input name='event_label' className='controlInput' placeholder='Event label' required/><select name='status' className='controlInput'><option>PLANNED</option><option>READY</option><option>IN_PROGRESS</option><option>COMPLETED</option><option>BLOCKED</option><option>CANCELLED</option></select><input name='occurred_at' type='datetime-local' className='controlInput'/><input name='location_label' className='controlInput' placeholder='Location'/><input name='evidence_uri' className='controlInput' placeholder='Evidence URI'/><input name='notes' className='controlInput' placeholder='Notes'/><button className='controlButton'>Record milestone</button></form></section>
 <section className='sectionCard'><div className='dashHead'><div><span className='eyebrow'>JOURNEY TIMELINE</span><h3>Registered events</h3></div></div><div className='controlRows'>{(e??[]).map(x=><form action={updateJourneyEvent} className='controlRow' key={x.id}><input type='hidden' name='id' value={x.id}/><span>{rm.get(x.registration_id)} · {dm.get(x.departure_id)} </span><input name='event_label' className='controlInput' defaultValue={x.event_label}/><select name='status' className='controlInput' defaultValue={x.status}><option>PLANNED</option><option>READY</option><option>IN_PROGRESS</option><option>COMPLETED</option><option>BLOCKED</option><option>CANCELLED</option></select><input name='occurred_at' type='datetime-local' className='controlInput' defaultValue={x.occurred_at?new Date(x.occurred_at).toISOString().slice(0,16):''}/><input name='location_label' className='controlInput' defaultValue={x.location_label??''}/><input name='evidence_uri' className='controlInput' defaultValue={x.evidence_uri??''}/><input name='notes' className='controlInput' defaultValue={x.notes??''}/><button className='controlButton'>Save</button></form>)}</div></section></main>
}